import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AuthGuard from "@/guard/auth-guard";
import AppMainLayout from "@/layouts/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <AntdRegistry>
      <AuthGuard>
        <AppMainLayout>{children}</AppMainLayout>
      </AuthGuard>
    </AntdRegistry>
  );
}
