"use client";

import { Inter } from "next/font/google";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };
const inter = Inter({ subsets: ["latin"] });
const queryClient = new QueryClient();

import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
